/********************************************************************************
** Form generated from reading UI file 'dicontrol.ui'
**
** Created: Mon Jul 2 23:56:44 2018
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DICONTROL_H
#define UI_DICONTROL_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_DIControl
{
public:
    QLabel *TrainType1;
    QLabel *TrainType4;
    QLabel *lblTitle_2;
    QLabel *lblTitle_7;
    QLabel *TrainType3;
    QLabel *TrainType2;
    QLabel *lblTitle_3;
    QLabel *lblTitle_9;
    QLabel *lbl_CH1;
    QLabel *lbl_CH1_State1;
    QLabel *lbl_CH1_State2;
    QLabel *lbl_CH13;
    QLabel *lbl_CH13_State1;
    QLabel *lbl_CH13_Name;
    QLabel *lbl_CH1_Name;
    QLabel *lbl_CH13_State2;
    QLabel *lbl_CH14_State2;
    QLabel *lbl_CH14_State1;
    QLabel *lbl_CH2_State2;
    QLabel *lbl_CH2_Name;
    QLabel *lbl_CH14_Name;
    QLabel *lbl_CH14;
    QLabel *lbl_CH2_State1;
    QLabel *lbl_CH2;
    QLabel *lbl_CH15;
    QLabel *lbl_CH3;
    QLabel *lbl_CH15_Name;
    QLabel *lbl_CH3_State1;
    QLabel *lbl_CH15_State2;
    QLabel *lbl_CH3_Name;
    QLabel *lbl_CH15_State1;
    QLabel *lbl_CH3_State2;
    QLabel *lbl_CH16_State2;
    QLabel *lbl_CH4_Name;
    QLabel *lbl_CH4_State2;
    QLabel *lbl_CH16_Name;
    QLabel *lbl_CH4;
    QLabel *lbl_CH4_State1;
    QLabel *lbl_CH16;
    QLabel *lbl_CH16_State1;
    QLabel *lbl_CH17;
    QLabel *lbl_CH5;
    QLabel *lbl_CH17_Name;
    QLabel *lbl_CH5_State1;
    QLabel *lbl_CH5_Name;
    QLabel *lbl_CH17_State2;
    QLabel *lbl_CH17_State1;
    QLabel *lbl_CH5_State2;
    QLabel *lbl_CH18;
    QLabel *lbl_CH6;
    QLabel *lbl_CH18_Name;
    QLabel *lbl_CH6_State1;
    QLabel *lbl_CH6_Name;
    QLabel *lbl_CH18_State2;
    QLabel *lbl_CH18_State1;
    QLabel *lbl_CH6_State2;
    QLabel *lbl_CH7_State1;
    QLabel *lbl_CH7_Name;
    QLabel *lbl_CH19_State2;
    QLabel *lbl_CH19_Name;
    QLabel *lbl_CH7;
    QLabel *lbl_CH7_State2;
    QLabel *lbl_CH19;
    QLabel *lbl_CH19_State1;
    QLabel *lbl_CH8_State1;
    QLabel *lbl_CH8_Name;
    QLabel *lbl_CH20_Name;
    QLabel *lbl_CH8;
    QLabel *lbl_CH8_State2;
    QLabel *lbl_CH20_State2;
    QLabel *lbl_CH20;
    QLabel *lbl_CH20_State1;
    QLabel *lbl_CH21_State2;
    QLabel *lbl_CH21_State1;
    QLabel *lbl_CH21_Name;
    QLabel *lbl_CH9;
    QLabel *lbl_CH9_State1;
    QLabel *lbl_CH9_Name;
    QLabel *lbl_CH21;
    QLabel *lbl_CH9_State2;
    QLabel *lbl_CH22;
    QLabel *lbl_CH10;
    QLabel *lbl_CH10_State1;
    QLabel *lbl_CH22_Name;
    QLabel *lbl_CH22_State1;
    QLabel *lbl_CH10_Name;
    QLabel *lbl_CH10_State2;
    QLabel *lbl_CH22_State2;
    QLabel *lbl_CH23_Name;
    QLabel *lbl_CH11_State1;
    QLabel *lbl_CH23_State1;
    QLabel *lbl_CH11;
    QLabel *lbl_CH11_Name;
    QLabel *lbl_CH23_State2;
    QLabel *lbl_CH11_State2;
    QLabel *lbl_CH23;
    QLabel *lbl_CH24;
    QLabel *lbl_CH12_State1;
    QLabel *lbl_CH12;
    QLabel *lbl_CH12_State2;
    QLabel *lbl_CH12_Name;
    QLabel *lbl_CH24_Name;
    QLabel *lbl_CH24_State2;
    QLabel *lbl_CH24_State1;

    void setupUi(QWidget *DIControl)
    {
        if (DIControl->objectName().isEmpty())
            DIControl->setObjectName(QString::fromUtf8("DIControl"));
        DIControl->resize(794, 380);
        DIControl->setStyleSheet(QString::fromUtf8("QWidget\n"
"{\n"
"background-color: rgb(0, 0, 50);\n"
"}\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"	font: 16px \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	color: white;\n"
"	border:2px solid white;\n"
"	background-color:black;\n"
"}"));
        TrainType1 = new QLabel(DIControl);
        TrainType1->setObjectName(QString::fromUtf8("TrainType1"));
        TrainType1->setGeometry(QRect(297, 0, 51, 31));
        TrainType1->setAlignment(Qt::AlignCenter);
        TrainType4 = new QLabel(DIControl);
        TrainType4->setObjectName(QString::fromUtf8("TrainType4"));
        TrainType4->setGeometry(QRect(741, 0, 51, 31));
        TrainType4->setAlignment(Qt::AlignCenter);
        lblTitle_2 = new QLabel(DIControl);
        lblTitle_2->setObjectName(QString::fromUtf8("lblTitle_2"));
        lblTitle_2->setGeometry(QRect(0, 0, 71, 31));
        lblTitle_2->setAlignment(Qt::AlignCenter);
        lblTitle_7 = new QLabel(DIControl);
        lblTitle_7->setObjectName(QString::fromUtf8("lblTitle_7"));
        lblTitle_7->setGeometry(QRect(464, 0, 230, 31));
        lblTitle_7->setAlignment(Qt::AlignCenter);
        TrainType3 = new QLabel(DIControl);
        TrainType3->setObjectName(QString::fromUtf8("TrainType3"));
        TrainType3->setGeometry(QRect(692, 0, 51, 31));
        TrainType3->setAlignment(Qt::AlignCenter);
        TrainType2 = new QLabel(DIControl);
        TrainType2->setObjectName(QString::fromUtf8("TrainType2"));
        TrainType2->setGeometry(QRect(346, 0, 51, 31));
        TrainType2->setAlignment(Qt::AlignCenter);
        lblTitle_3 = new QLabel(DIControl);
        lblTitle_3->setObjectName(QString::fromUtf8("lblTitle_3"));
        lblTitle_3->setGeometry(QRect(69, 0, 230, 31));
        lblTitle_3->setAlignment(Qt::AlignCenter);
        lblTitle_9 = new QLabel(DIControl);
        lblTitle_9->setObjectName(QString::fromUtf8("lblTitle_9"));
        lblTitle_9->setGeometry(QRect(395, 0, 71, 31));
        lblTitle_9->setAlignment(Qt::AlignCenter);
        lbl_CH1 = new QLabel(DIControl);
        lbl_CH1->setObjectName(QString::fromUtf8("lbl_CH1"));
        lbl_CH1->setGeometry(QRect(0, 29, 71, 31));
        lbl_CH1->setAlignment(Qt::AlignCenter);
        lbl_CH1_State1 = new QLabel(DIControl);
        lbl_CH1_State1->setObjectName(QString::fromUtf8("lbl_CH1_State1"));
        lbl_CH1_State1->setGeometry(QRect(297, 29, 51, 31));
        lbl_CH1_State1->setAlignment(Qt::AlignCenter);
        lbl_CH1_State2 = new QLabel(DIControl);
        lbl_CH1_State2->setObjectName(QString::fromUtf8("lbl_CH1_State2"));
        lbl_CH1_State2->setGeometry(QRect(346, 29, 51, 31));
        lbl_CH1_State2->setAlignment(Qt::AlignCenter);
        lbl_CH13 = new QLabel(DIControl);
        lbl_CH13->setObjectName(QString::fromUtf8("lbl_CH13"));
        lbl_CH13->setGeometry(QRect(395, 29, 71, 31));
        lbl_CH13->setAlignment(Qt::AlignCenter);
        lbl_CH13_State1 = new QLabel(DIControl);
        lbl_CH13_State1->setObjectName(QString::fromUtf8("lbl_CH13_State1"));
        lbl_CH13_State1->setGeometry(QRect(692, 29, 51, 31));
        lbl_CH13_State1->setAlignment(Qt::AlignCenter);
        lbl_CH13_Name = new QLabel(DIControl);
        lbl_CH13_Name->setObjectName(QString::fromUtf8("lbl_CH13_Name"));
        lbl_CH13_Name->setGeometry(QRect(464, 29, 230, 31));
        lbl_CH13_Name->setAlignment(Qt::AlignCenter);
        lbl_CH1_Name = new QLabel(DIControl);
        lbl_CH1_Name->setObjectName(QString::fromUtf8("lbl_CH1_Name"));
        lbl_CH1_Name->setGeometry(QRect(69, 29, 230, 31));
        lbl_CH1_Name->setAlignment(Qt::AlignCenter);
        lbl_CH13_State2 = new QLabel(DIControl);
        lbl_CH13_State2->setObjectName(QString::fromUtf8("lbl_CH13_State2"));
        lbl_CH13_State2->setGeometry(QRect(741, 29, 51, 31));
        lbl_CH13_State2->setAlignment(Qt::AlignCenter);
        lbl_CH14_State2 = new QLabel(DIControl);
        lbl_CH14_State2->setObjectName(QString::fromUtf8("lbl_CH14_State2"));
        lbl_CH14_State2->setGeometry(QRect(741, 58, 51, 31));
        lbl_CH14_State2->setAlignment(Qt::AlignCenter);
        lbl_CH14_State1 = new QLabel(DIControl);
        lbl_CH14_State1->setObjectName(QString::fromUtf8("lbl_CH14_State1"));
        lbl_CH14_State1->setGeometry(QRect(692, 58, 51, 31));
        lbl_CH14_State1->setAlignment(Qt::AlignCenter);
        lbl_CH2_State2 = new QLabel(DIControl);
        lbl_CH2_State2->setObjectName(QString::fromUtf8("lbl_CH2_State2"));
        lbl_CH2_State2->setGeometry(QRect(346, 58, 51, 31));
        lbl_CH2_State2->setAlignment(Qt::AlignCenter);
        lbl_CH2_Name = new QLabel(DIControl);
        lbl_CH2_Name->setObjectName(QString::fromUtf8("lbl_CH2_Name"));
        lbl_CH2_Name->setGeometry(QRect(69, 58, 230, 31));
        lbl_CH2_Name->setAlignment(Qt::AlignCenter);
        lbl_CH14_Name = new QLabel(DIControl);
        lbl_CH14_Name->setObjectName(QString::fromUtf8("lbl_CH14_Name"));
        lbl_CH14_Name->setGeometry(QRect(464, 58, 230, 31));
        lbl_CH14_Name->setAlignment(Qt::AlignCenter);
        lbl_CH14 = new QLabel(DIControl);
        lbl_CH14->setObjectName(QString::fromUtf8("lbl_CH14"));
        lbl_CH14->setGeometry(QRect(395, 58, 71, 31));
        lbl_CH14->setAlignment(Qt::AlignCenter);
        lbl_CH2_State1 = new QLabel(DIControl);
        lbl_CH2_State1->setObjectName(QString::fromUtf8("lbl_CH2_State1"));
        lbl_CH2_State1->setGeometry(QRect(297, 58, 51, 31));
        lbl_CH2_State1->setAlignment(Qt::AlignCenter);
        lbl_CH2 = new QLabel(DIControl);
        lbl_CH2->setObjectName(QString::fromUtf8("lbl_CH2"));
        lbl_CH2->setGeometry(QRect(0, 58, 71, 31));
        lbl_CH2->setAlignment(Qt::AlignCenter);
        lbl_CH15 = new QLabel(DIControl);
        lbl_CH15->setObjectName(QString::fromUtf8("lbl_CH15"));
        lbl_CH15->setGeometry(QRect(395, 87, 71, 31));
        lbl_CH15->setAlignment(Qt::AlignCenter);
        lbl_CH3 = new QLabel(DIControl);
        lbl_CH3->setObjectName(QString::fromUtf8("lbl_CH3"));
        lbl_CH3->setGeometry(QRect(0, 87, 71, 31));
        lbl_CH3->setAlignment(Qt::AlignCenter);
        lbl_CH15_Name = new QLabel(DIControl);
        lbl_CH15_Name->setObjectName(QString::fromUtf8("lbl_CH15_Name"));
        lbl_CH15_Name->setGeometry(QRect(464, 87, 230, 31));
        lbl_CH15_Name->setAlignment(Qt::AlignCenter);
        lbl_CH3_State1 = new QLabel(DIControl);
        lbl_CH3_State1->setObjectName(QString::fromUtf8("lbl_CH3_State1"));
        lbl_CH3_State1->setGeometry(QRect(297, 87, 51, 31));
        lbl_CH3_State1->setAlignment(Qt::AlignCenter);
        lbl_CH15_State2 = new QLabel(DIControl);
        lbl_CH15_State2->setObjectName(QString::fromUtf8("lbl_CH15_State2"));
        lbl_CH15_State2->setGeometry(QRect(741, 87, 51, 31));
        lbl_CH15_State2->setAlignment(Qt::AlignCenter);
        lbl_CH3_Name = new QLabel(DIControl);
        lbl_CH3_Name->setObjectName(QString::fromUtf8("lbl_CH3_Name"));
        lbl_CH3_Name->setGeometry(QRect(69, 87, 230, 31));
        lbl_CH3_Name->setAlignment(Qt::AlignCenter);
        lbl_CH15_State1 = new QLabel(DIControl);
        lbl_CH15_State1->setObjectName(QString::fromUtf8("lbl_CH15_State1"));
        lbl_CH15_State1->setGeometry(QRect(692, 87, 51, 31));
        lbl_CH15_State1->setAlignment(Qt::AlignCenter);
        lbl_CH3_State2 = new QLabel(DIControl);
        lbl_CH3_State2->setObjectName(QString::fromUtf8("lbl_CH3_State2"));
        lbl_CH3_State2->setGeometry(QRect(346, 87, 51, 31));
        lbl_CH3_State2->setAlignment(Qt::AlignCenter);
        lbl_CH16_State2 = new QLabel(DIControl);
        lbl_CH16_State2->setObjectName(QString::fromUtf8("lbl_CH16_State2"));
        lbl_CH16_State2->setGeometry(QRect(741, 116, 51, 31));
        lbl_CH16_State2->setAlignment(Qt::AlignCenter);
        lbl_CH4_Name = new QLabel(DIControl);
        lbl_CH4_Name->setObjectName(QString::fromUtf8("lbl_CH4_Name"));
        lbl_CH4_Name->setGeometry(QRect(69, 116, 230, 31));
        lbl_CH4_Name->setAlignment(Qt::AlignCenter);
        lbl_CH4_State2 = new QLabel(DIControl);
        lbl_CH4_State2->setObjectName(QString::fromUtf8("lbl_CH4_State2"));
        lbl_CH4_State2->setGeometry(QRect(346, 116, 51, 31));
        lbl_CH4_State2->setAlignment(Qt::AlignCenter);
        lbl_CH16_Name = new QLabel(DIControl);
        lbl_CH16_Name->setObjectName(QString::fromUtf8("lbl_CH16_Name"));
        lbl_CH16_Name->setGeometry(QRect(464, 116, 230, 31));
        lbl_CH16_Name->setAlignment(Qt::AlignCenter);
        lbl_CH4 = new QLabel(DIControl);
        lbl_CH4->setObjectName(QString::fromUtf8("lbl_CH4"));
        lbl_CH4->setGeometry(QRect(0, 116, 71, 31));
        lbl_CH4->setAlignment(Qt::AlignCenter);
        lbl_CH4_State1 = new QLabel(DIControl);
        lbl_CH4_State1->setObjectName(QString::fromUtf8("lbl_CH4_State1"));
        lbl_CH4_State1->setGeometry(QRect(297, 116, 51, 31));
        lbl_CH4_State1->setAlignment(Qt::AlignCenter);
        lbl_CH16 = new QLabel(DIControl);
        lbl_CH16->setObjectName(QString::fromUtf8("lbl_CH16"));
        lbl_CH16->setGeometry(QRect(395, 116, 71, 31));
        lbl_CH16->setAlignment(Qt::AlignCenter);
        lbl_CH16_State1 = new QLabel(DIControl);
        lbl_CH16_State1->setObjectName(QString::fromUtf8("lbl_CH16_State1"));
        lbl_CH16_State1->setGeometry(QRect(692, 116, 51, 31));
        lbl_CH16_State1->setAlignment(Qt::AlignCenter);
        lbl_CH17 = new QLabel(DIControl);
        lbl_CH17->setObjectName(QString::fromUtf8("lbl_CH17"));
        lbl_CH17->setGeometry(QRect(395, 144, 71, 31));
        lbl_CH17->setAlignment(Qt::AlignCenter);
        lbl_CH5 = new QLabel(DIControl);
        lbl_CH5->setObjectName(QString::fromUtf8("lbl_CH5"));
        lbl_CH5->setGeometry(QRect(0, 144, 71, 31));
        lbl_CH5->setAlignment(Qt::AlignCenter);
        lbl_CH17_Name = new QLabel(DIControl);
        lbl_CH17_Name->setObjectName(QString::fromUtf8("lbl_CH17_Name"));
        lbl_CH17_Name->setGeometry(QRect(464, 144, 230, 31));
        lbl_CH17_Name->setAlignment(Qt::AlignCenter);
        lbl_CH5_State1 = new QLabel(DIControl);
        lbl_CH5_State1->setObjectName(QString::fromUtf8("lbl_CH5_State1"));
        lbl_CH5_State1->setGeometry(QRect(297, 144, 51, 31));
        lbl_CH5_State1->setAlignment(Qt::AlignCenter);
        lbl_CH5_Name = new QLabel(DIControl);
        lbl_CH5_Name->setObjectName(QString::fromUtf8("lbl_CH5_Name"));
        lbl_CH5_Name->setGeometry(QRect(69, 144, 230, 31));
        lbl_CH5_Name->setAlignment(Qt::AlignCenter);
        lbl_CH17_State2 = new QLabel(DIControl);
        lbl_CH17_State2->setObjectName(QString::fromUtf8("lbl_CH17_State2"));
        lbl_CH17_State2->setGeometry(QRect(741, 144, 51, 31));
        lbl_CH17_State2->setAlignment(Qt::AlignCenter);
        lbl_CH17_State1 = new QLabel(DIControl);
        lbl_CH17_State1->setObjectName(QString::fromUtf8("lbl_CH17_State1"));
        lbl_CH17_State1->setGeometry(QRect(692, 144, 51, 31));
        lbl_CH17_State1->setAlignment(Qt::AlignCenter);
        lbl_CH5_State2 = new QLabel(DIControl);
        lbl_CH5_State2->setObjectName(QString::fromUtf8("lbl_CH5_State2"));
        lbl_CH5_State2->setGeometry(QRect(346, 144, 51, 31));
        lbl_CH5_State2->setAlignment(Qt::AlignCenter);
        lbl_CH18 = new QLabel(DIControl);
        lbl_CH18->setObjectName(QString::fromUtf8("lbl_CH18"));
        lbl_CH18->setGeometry(QRect(395, 173, 71, 31));
        lbl_CH18->setAlignment(Qt::AlignCenter);
        lbl_CH6 = new QLabel(DIControl);
        lbl_CH6->setObjectName(QString::fromUtf8("lbl_CH6"));
        lbl_CH6->setGeometry(QRect(0, 173, 71, 31));
        lbl_CH6->setAlignment(Qt::AlignCenter);
        lbl_CH18_Name = new QLabel(DIControl);
        lbl_CH18_Name->setObjectName(QString::fromUtf8("lbl_CH18_Name"));
        lbl_CH18_Name->setGeometry(QRect(464, 173, 230, 31));
        lbl_CH18_Name->setAlignment(Qt::AlignCenter);
        lbl_CH6_State1 = new QLabel(DIControl);
        lbl_CH6_State1->setObjectName(QString::fromUtf8("lbl_CH6_State1"));
        lbl_CH6_State1->setGeometry(QRect(297, 173, 51, 31));
        lbl_CH6_State1->setAlignment(Qt::AlignCenter);
        lbl_CH6_Name = new QLabel(DIControl);
        lbl_CH6_Name->setObjectName(QString::fromUtf8("lbl_CH6_Name"));
        lbl_CH6_Name->setGeometry(QRect(69, 173, 230, 31));
        lbl_CH6_Name->setAlignment(Qt::AlignCenter);
        lbl_CH18_State2 = new QLabel(DIControl);
        lbl_CH18_State2->setObjectName(QString::fromUtf8("lbl_CH18_State2"));
        lbl_CH18_State2->setGeometry(QRect(741, 173, 51, 31));
        lbl_CH18_State2->setAlignment(Qt::AlignCenter);
        lbl_CH18_State1 = new QLabel(DIControl);
        lbl_CH18_State1->setObjectName(QString::fromUtf8("lbl_CH18_State1"));
        lbl_CH18_State1->setGeometry(QRect(692, 173, 51, 31));
        lbl_CH18_State1->setAlignment(Qt::AlignCenter);
        lbl_CH6_State2 = new QLabel(DIControl);
        lbl_CH6_State2->setObjectName(QString::fromUtf8("lbl_CH6_State2"));
        lbl_CH6_State2->setGeometry(QRect(346, 173, 51, 31));
        lbl_CH6_State2->setAlignment(Qt::AlignCenter);
        lbl_CH7_State1 = new QLabel(DIControl);
        lbl_CH7_State1->setObjectName(QString::fromUtf8("lbl_CH7_State1"));
        lbl_CH7_State1->setGeometry(QRect(297, 202, 51, 31));
        lbl_CH7_State1->setAlignment(Qt::AlignCenter);
        lbl_CH7_Name = new QLabel(DIControl);
        lbl_CH7_Name->setObjectName(QString::fromUtf8("lbl_CH7_Name"));
        lbl_CH7_Name->setGeometry(QRect(69, 202, 230, 31));
        lbl_CH7_Name->setAlignment(Qt::AlignCenter);
        lbl_CH19_State2 = new QLabel(DIControl);
        lbl_CH19_State2->setObjectName(QString::fromUtf8("lbl_CH19_State2"));
        lbl_CH19_State2->setGeometry(QRect(741, 202, 51, 31));
        lbl_CH19_State2->setAlignment(Qt::AlignCenter);
        lbl_CH19_Name = new QLabel(DIControl);
        lbl_CH19_Name->setObjectName(QString::fromUtf8("lbl_CH19_Name"));
        lbl_CH19_Name->setGeometry(QRect(464, 202, 230, 31));
        lbl_CH19_Name->setAlignment(Qt::AlignCenter);
        lbl_CH7 = new QLabel(DIControl);
        lbl_CH7->setObjectName(QString::fromUtf8("lbl_CH7"));
        lbl_CH7->setGeometry(QRect(0, 202, 71, 31));
        lbl_CH7->setAlignment(Qt::AlignCenter);
        lbl_CH7_State2 = new QLabel(DIControl);
        lbl_CH7_State2->setObjectName(QString::fromUtf8("lbl_CH7_State2"));
        lbl_CH7_State2->setGeometry(QRect(346, 202, 51, 31));
        lbl_CH7_State2->setAlignment(Qt::AlignCenter);
        lbl_CH19 = new QLabel(DIControl);
        lbl_CH19->setObjectName(QString::fromUtf8("lbl_CH19"));
        lbl_CH19->setGeometry(QRect(395, 202, 71, 31));
        lbl_CH19->setAlignment(Qt::AlignCenter);
        lbl_CH19_State1 = new QLabel(DIControl);
        lbl_CH19_State1->setObjectName(QString::fromUtf8("lbl_CH19_State1"));
        lbl_CH19_State1->setGeometry(QRect(692, 202, 51, 31));
        lbl_CH19_State1->setAlignment(Qt::AlignCenter);
        lbl_CH8_State1 = new QLabel(DIControl);
        lbl_CH8_State1->setObjectName(QString::fromUtf8("lbl_CH8_State1"));
        lbl_CH8_State1->setGeometry(QRect(297, 231, 51, 31));
        lbl_CH8_State1->setAlignment(Qt::AlignCenter);
        lbl_CH8_Name = new QLabel(DIControl);
        lbl_CH8_Name->setObjectName(QString::fromUtf8("lbl_CH8_Name"));
        lbl_CH8_Name->setGeometry(QRect(69, 231, 230, 31));
        lbl_CH8_Name->setAlignment(Qt::AlignCenter);
        lbl_CH20_Name = new QLabel(DIControl);
        lbl_CH20_Name->setObjectName(QString::fromUtf8("lbl_CH20_Name"));
        lbl_CH20_Name->setGeometry(QRect(464, 231, 230, 31));
        lbl_CH20_Name->setAlignment(Qt::AlignCenter);
        lbl_CH8 = new QLabel(DIControl);
        lbl_CH8->setObjectName(QString::fromUtf8("lbl_CH8"));
        lbl_CH8->setGeometry(QRect(0, 231, 71, 31));
        lbl_CH8->setAlignment(Qt::AlignCenter);
        lbl_CH8_State2 = new QLabel(DIControl);
        lbl_CH8_State2->setObjectName(QString::fromUtf8("lbl_CH8_State2"));
        lbl_CH8_State2->setGeometry(QRect(346, 231, 51, 31));
        lbl_CH8_State2->setAlignment(Qt::AlignCenter);
        lbl_CH20_State2 = new QLabel(DIControl);
        lbl_CH20_State2->setObjectName(QString::fromUtf8("lbl_CH20_State2"));
        lbl_CH20_State2->setGeometry(QRect(741, 231, 51, 31));
        lbl_CH20_State2->setAlignment(Qt::AlignCenter);
        lbl_CH20 = new QLabel(DIControl);
        lbl_CH20->setObjectName(QString::fromUtf8("lbl_CH20"));
        lbl_CH20->setGeometry(QRect(395, 231, 71, 31));
        lbl_CH20->setAlignment(Qt::AlignCenter);
        lbl_CH20_State1 = new QLabel(DIControl);
        lbl_CH20_State1->setObjectName(QString::fromUtf8("lbl_CH20_State1"));
        lbl_CH20_State1->setGeometry(QRect(692, 231, 51, 31));
        lbl_CH20_State1->setAlignment(Qt::AlignCenter);
        lbl_CH21_State2 = new QLabel(DIControl);
        lbl_CH21_State2->setObjectName(QString::fromUtf8("lbl_CH21_State2"));
        lbl_CH21_State2->setGeometry(QRect(741, 260, 51, 31));
        lbl_CH21_State2->setAlignment(Qt::AlignCenter);
        lbl_CH21_State1 = new QLabel(DIControl);
        lbl_CH21_State1->setObjectName(QString::fromUtf8("lbl_CH21_State1"));
        lbl_CH21_State1->setGeometry(QRect(692, 260, 51, 31));
        lbl_CH21_State1->setAlignment(Qt::AlignCenter);
        lbl_CH21_Name = new QLabel(DIControl);
        lbl_CH21_Name->setObjectName(QString::fromUtf8("lbl_CH21_Name"));
        lbl_CH21_Name->setGeometry(QRect(464, 260, 230, 31));
        lbl_CH21_Name->setAlignment(Qt::AlignCenter);
        lbl_CH9 = new QLabel(DIControl);
        lbl_CH9->setObjectName(QString::fromUtf8("lbl_CH9"));
        lbl_CH9->setGeometry(QRect(0, 260, 71, 31));
        lbl_CH9->setAlignment(Qt::AlignCenter);
        lbl_CH9_State1 = new QLabel(DIControl);
        lbl_CH9_State1->setObjectName(QString::fromUtf8("lbl_CH9_State1"));
        lbl_CH9_State1->setGeometry(QRect(297, 260, 51, 31));
        lbl_CH9_State1->setAlignment(Qt::AlignCenter);
        lbl_CH9_Name = new QLabel(DIControl);
        lbl_CH9_Name->setObjectName(QString::fromUtf8("lbl_CH9_Name"));
        lbl_CH9_Name->setGeometry(QRect(69, 260, 230, 31));
        lbl_CH9_Name->setAlignment(Qt::AlignCenter);
        lbl_CH21 = new QLabel(DIControl);
        lbl_CH21->setObjectName(QString::fromUtf8("lbl_CH21"));
        lbl_CH21->setGeometry(QRect(395, 260, 71, 31));
        lbl_CH21->setAlignment(Qt::AlignCenter);
        lbl_CH9_State2 = new QLabel(DIControl);
        lbl_CH9_State2->setObjectName(QString::fromUtf8("lbl_CH9_State2"));
        lbl_CH9_State2->setGeometry(QRect(346, 260, 51, 31));
        lbl_CH9_State2->setAlignment(Qt::AlignCenter);
        lbl_CH22 = new QLabel(DIControl);
        lbl_CH22->setObjectName(QString::fromUtf8("lbl_CH22"));
        lbl_CH22->setGeometry(QRect(395, 289, 71, 31));
        lbl_CH22->setAlignment(Qt::AlignCenter);
        lbl_CH10 = new QLabel(DIControl);
        lbl_CH10->setObjectName(QString::fromUtf8("lbl_CH10"));
        lbl_CH10->setGeometry(QRect(0, 289, 71, 31));
        lbl_CH10->setAlignment(Qt::AlignCenter);
        lbl_CH10_State1 = new QLabel(DIControl);
        lbl_CH10_State1->setObjectName(QString::fromUtf8("lbl_CH10_State1"));
        lbl_CH10_State1->setGeometry(QRect(297, 289, 51, 31));
        lbl_CH10_State1->setAlignment(Qt::AlignCenter);
        lbl_CH22_Name = new QLabel(DIControl);
        lbl_CH22_Name->setObjectName(QString::fromUtf8("lbl_CH22_Name"));
        lbl_CH22_Name->setGeometry(QRect(464, 289, 230, 31));
        lbl_CH22_Name->setAlignment(Qt::AlignCenter);
        lbl_CH22_State1 = new QLabel(DIControl);
        lbl_CH22_State1->setObjectName(QString::fromUtf8("lbl_CH22_State1"));
        lbl_CH22_State1->setGeometry(QRect(692, 289, 51, 31));
        lbl_CH22_State1->setAlignment(Qt::AlignCenter);
        lbl_CH10_Name = new QLabel(DIControl);
        lbl_CH10_Name->setObjectName(QString::fromUtf8("lbl_CH10_Name"));
        lbl_CH10_Name->setGeometry(QRect(69, 289, 230, 31));
        lbl_CH10_Name->setAlignment(Qt::AlignCenter);
        lbl_CH10_State2 = new QLabel(DIControl);
        lbl_CH10_State2->setObjectName(QString::fromUtf8("lbl_CH10_State2"));
        lbl_CH10_State2->setGeometry(QRect(346, 289, 51, 31));
        lbl_CH10_State2->setAlignment(Qt::AlignCenter);
        lbl_CH22_State2 = new QLabel(DIControl);
        lbl_CH22_State2->setObjectName(QString::fromUtf8("lbl_CH22_State2"));
        lbl_CH22_State2->setGeometry(QRect(741, 289, 51, 31));
        lbl_CH22_State2->setAlignment(Qt::AlignCenter);
        lbl_CH23_Name = new QLabel(DIControl);
        lbl_CH23_Name->setObjectName(QString::fromUtf8("lbl_CH23_Name"));
        lbl_CH23_Name->setGeometry(QRect(464, 318, 230, 31));
        lbl_CH23_Name->setAlignment(Qt::AlignCenter);
        lbl_CH11_State1 = new QLabel(DIControl);
        lbl_CH11_State1->setObjectName(QString::fromUtf8("lbl_CH11_State1"));
        lbl_CH11_State1->setGeometry(QRect(297, 318, 51, 31));
        lbl_CH11_State1->setAlignment(Qt::AlignCenter);
        lbl_CH23_State1 = new QLabel(DIControl);
        lbl_CH23_State1->setObjectName(QString::fromUtf8("lbl_CH23_State1"));
        lbl_CH23_State1->setGeometry(QRect(692, 318, 51, 31));
        lbl_CH23_State1->setAlignment(Qt::AlignCenter);
        lbl_CH11 = new QLabel(DIControl);
        lbl_CH11->setObjectName(QString::fromUtf8("lbl_CH11"));
        lbl_CH11->setGeometry(QRect(0, 318, 71, 31));
        lbl_CH11->setAlignment(Qt::AlignCenter);
        lbl_CH11_Name = new QLabel(DIControl);
        lbl_CH11_Name->setObjectName(QString::fromUtf8("lbl_CH11_Name"));
        lbl_CH11_Name->setGeometry(QRect(69, 318, 230, 31));
        lbl_CH11_Name->setAlignment(Qt::AlignCenter);
        lbl_CH23_State2 = new QLabel(DIControl);
        lbl_CH23_State2->setObjectName(QString::fromUtf8("lbl_CH23_State2"));
        lbl_CH23_State2->setGeometry(QRect(741, 318, 51, 31));
        lbl_CH23_State2->setAlignment(Qt::AlignCenter);
        lbl_CH11_State2 = new QLabel(DIControl);
        lbl_CH11_State2->setObjectName(QString::fromUtf8("lbl_CH11_State2"));
        lbl_CH11_State2->setGeometry(QRect(346, 318, 51, 31));
        lbl_CH11_State2->setAlignment(Qt::AlignCenter);
        lbl_CH23 = new QLabel(DIControl);
        lbl_CH23->setObjectName(QString::fromUtf8("lbl_CH23"));
        lbl_CH23->setGeometry(QRect(395, 318, 71, 31));
        lbl_CH23->setAlignment(Qt::AlignCenter);
        lbl_CH24 = new QLabel(DIControl);
        lbl_CH24->setObjectName(QString::fromUtf8("lbl_CH24"));
        lbl_CH24->setGeometry(QRect(395, 347, 71, 31));
        lbl_CH24->setAlignment(Qt::AlignCenter);
        lbl_CH12_State1 = new QLabel(DIControl);
        lbl_CH12_State1->setObjectName(QString::fromUtf8("lbl_CH12_State1"));
        lbl_CH12_State1->setGeometry(QRect(297, 347, 51, 31));
        lbl_CH12_State1->setAlignment(Qt::AlignCenter);
        lbl_CH12 = new QLabel(DIControl);
        lbl_CH12->setObjectName(QString::fromUtf8("lbl_CH12"));
        lbl_CH12->setGeometry(QRect(0, 347, 71, 31));
        lbl_CH12->setAlignment(Qt::AlignCenter);
        lbl_CH12_State2 = new QLabel(DIControl);
        lbl_CH12_State2->setObjectName(QString::fromUtf8("lbl_CH12_State2"));
        lbl_CH12_State2->setGeometry(QRect(346, 347, 51, 31));
        lbl_CH12_State2->setAlignment(Qt::AlignCenter);
        lbl_CH12_Name = new QLabel(DIControl);
        lbl_CH12_Name->setObjectName(QString::fromUtf8("lbl_CH12_Name"));
        lbl_CH12_Name->setGeometry(QRect(69, 347, 230, 31));
        lbl_CH12_Name->setAlignment(Qt::AlignCenter);
        lbl_CH24_Name = new QLabel(DIControl);
        lbl_CH24_Name->setObjectName(QString::fromUtf8("lbl_CH24_Name"));
        lbl_CH24_Name->setGeometry(QRect(464, 347, 230, 31));
        lbl_CH24_Name->setAlignment(Qt::AlignCenter);
        lbl_CH24_State2 = new QLabel(DIControl);
        lbl_CH24_State2->setObjectName(QString::fromUtf8("lbl_CH24_State2"));
        lbl_CH24_State2->setGeometry(QRect(741, 347, 51, 31));
        lbl_CH24_State2->setAlignment(Qt::AlignCenter);
        lbl_CH24_State1 = new QLabel(DIControl);
        lbl_CH24_State1->setObjectName(QString::fromUtf8("lbl_CH24_State1"));
        lbl_CH24_State1->setGeometry(QRect(692, 347, 51, 31));
        lbl_CH24_State1->setAlignment(Qt::AlignCenter);

        retranslateUi(DIControl);

        QMetaObject::connectSlotsByName(DIControl);
    } // setupUi

    void retranslateUi(QWidget *DIControl)
    {
        DIControl->setWindowTitle(QApplication::translate("DIControl", "Form", 0, QApplication::UnicodeUTF8));
        TrainType1->setText(QString());
        TrainType4->setText(QString());
        lblTitle_2->setText(QApplication::translate("DIControl", "\351\200\232\351\201\223", 0, QApplication::UnicodeUTF8));
        lblTitle_7->setText(QApplication::translate("DIControl", "\344\277\241\345\217\267\345\220\215\347\247\260", 0, QApplication::UnicodeUTF8));
        TrainType3->setText(QString());
        TrainType2->setText(QString());
        lblTitle_3->setText(QApplication::translate("DIControl", "\344\277\241\345\217\267\345\220\215\347\247\260", 0, QApplication::UnicodeUTF8));
        lblTitle_9->setText(QApplication::translate("DIControl", "\351\200\232\351\201\223", 0, QApplication::UnicodeUTF8));
        lbl_CH1->setText(QApplication::translate("DIControl", "CH1", 0, QApplication::UnicodeUTF8));
        lbl_CH1_State1->setText(QString());
        lbl_CH1_State2->setText(QString());
        lbl_CH13->setText(QApplication::translate("DIControl", "CH13", 0, QApplication::UnicodeUTF8));
        lbl_CH13_State1->setText(QString());
        lbl_CH13_Name->setText(QString());
        lbl_CH1_Name->setText(QString());
        lbl_CH13_State2->setText(QString());
        lbl_CH14_State2->setText(QString());
        lbl_CH14_State1->setText(QString());
        lbl_CH2_State2->setText(QString());
        lbl_CH2_Name->setText(QString());
        lbl_CH14_Name->setText(QString());
        lbl_CH14->setText(QApplication::translate("DIControl", "CH14", 0, QApplication::UnicodeUTF8));
        lbl_CH2_State1->setText(QString());
        lbl_CH2->setText(QApplication::translate("DIControl", "CH2", 0, QApplication::UnicodeUTF8));
        lbl_CH15->setText(QApplication::translate("DIControl", "CH15", 0, QApplication::UnicodeUTF8));
        lbl_CH3->setText(QApplication::translate("DIControl", "CH3", 0, QApplication::UnicodeUTF8));
        lbl_CH15_Name->setText(QString());
        lbl_CH3_State1->setText(QString());
        lbl_CH15_State2->setText(QString());
        lbl_CH3_Name->setText(QString());
        lbl_CH15_State1->setText(QString());
        lbl_CH3_State2->setText(QString());
        lbl_CH16_State2->setText(QString());
        lbl_CH4_Name->setText(QString());
        lbl_CH4_State2->setText(QString());
        lbl_CH16_Name->setText(QString());
        lbl_CH4->setText(QApplication::translate("DIControl", "CH4", 0, QApplication::UnicodeUTF8));
        lbl_CH4_State1->setText(QString());
        lbl_CH16->setText(QApplication::translate("DIControl", "CH16", 0, QApplication::UnicodeUTF8));
        lbl_CH16_State1->setText(QString());
        lbl_CH17->setText(QApplication::translate("DIControl", "CH17", 0, QApplication::UnicodeUTF8));
        lbl_CH5->setText(QApplication::translate("DIControl", "CH5", 0, QApplication::UnicodeUTF8));
        lbl_CH17_Name->setText(QString());
        lbl_CH5_State1->setText(QString());
        lbl_CH5_Name->setText(QString());
        lbl_CH17_State2->setText(QString());
        lbl_CH17_State1->setText(QString());
        lbl_CH5_State2->setText(QString());
        lbl_CH18->setText(QApplication::translate("DIControl", "CH18", 0, QApplication::UnicodeUTF8));
        lbl_CH6->setText(QApplication::translate("DIControl", "CH6", 0, QApplication::UnicodeUTF8));
        lbl_CH18_Name->setText(QString());
        lbl_CH6_State1->setText(QString());
        lbl_CH6_Name->setText(QString());
        lbl_CH18_State2->setText(QString());
        lbl_CH18_State1->setText(QString());
        lbl_CH6_State2->setText(QString());
        lbl_CH7_State1->setText(QString());
        lbl_CH7_Name->setText(QString());
        lbl_CH19_State2->setText(QString());
        lbl_CH19_Name->setText(QString());
        lbl_CH7->setText(QApplication::translate("DIControl", "CH7", 0, QApplication::UnicodeUTF8));
        lbl_CH7_State2->setText(QString());
        lbl_CH19->setText(QApplication::translate("DIControl", "CH19", 0, QApplication::UnicodeUTF8));
        lbl_CH19_State1->setText(QString());
        lbl_CH8_State1->setText(QString());
        lbl_CH8_Name->setText(QString());
        lbl_CH20_Name->setText(QString());
        lbl_CH8->setText(QApplication::translate("DIControl", "CH8", 0, QApplication::UnicodeUTF8));
        lbl_CH8_State2->setText(QString());
        lbl_CH20_State2->setText(QString());
        lbl_CH20->setText(QApplication::translate("DIControl", "CH20", 0, QApplication::UnicodeUTF8));
        lbl_CH20_State1->setText(QString());
        lbl_CH21_State2->setText(QString());
        lbl_CH21_State1->setText(QString());
        lbl_CH21_Name->setText(QString());
        lbl_CH9->setText(QApplication::translate("DIControl", "CH9", 0, QApplication::UnicodeUTF8));
        lbl_CH9_State1->setText(QString());
        lbl_CH9_Name->setText(QString());
        lbl_CH21->setText(QApplication::translate("DIControl", "CH21", 0, QApplication::UnicodeUTF8));
        lbl_CH9_State2->setText(QString());
        lbl_CH22->setText(QApplication::translate("DIControl", "CH22", 0, QApplication::UnicodeUTF8));
        lbl_CH10->setText(QApplication::translate("DIControl", "CH10", 0, QApplication::UnicodeUTF8));
        lbl_CH10_State1->setText(QString());
        lbl_CH22_Name->setText(QString());
        lbl_CH22_State1->setText(QString());
        lbl_CH10_Name->setText(QString());
        lbl_CH10_State2->setText(QString());
        lbl_CH22_State2->setText(QString());
        lbl_CH23_Name->setText(QString());
        lbl_CH11_State1->setText(QString());
        lbl_CH23_State1->setText(QString());
        lbl_CH11->setText(QApplication::translate("DIControl", "CH11", 0, QApplication::UnicodeUTF8));
        lbl_CH11_Name->setText(QString());
        lbl_CH23_State2->setText(QString());
        lbl_CH11_State2->setText(QString());
        lbl_CH23->setText(QApplication::translate("DIControl", "CH23", 0, QApplication::UnicodeUTF8));
        lbl_CH24->setText(QApplication::translate("DIControl", "CH24", 0, QApplication::UnicodeUTF8));
        lbl_CH12_State1->setText(QString());
        lbl_CH12->setText(QApplication::translate("DIControl", "CH12", 0, QApplication::UnicodeUTF8));
        lbl_CH12_State2->setText(QString());
        lbl_CH12_Name->setText(QString());
        lbl_CH24_Name->setText(QString());
        lbl_CH24_State2->setText(QString());
        lbl_CH24_State1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class DIControl: public Ui_DIControl {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DICONTROL_H
