/********************************************************************************
** Form generated from reading UI file 'vehicletrainarea.ui'
**
** Created: Tue Jul 17 22:05:23 2018
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VEHICLETRAINAREA_H
#define UI_VEHICLETRAINAREA_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VehicleTrainArea
{
public:
    QLabel *lbl_door4_5;
    QLabel *lbl_door4_8;
    QLabel *lbl_door2_5;
    QLabel *LBLM1;
    QLabel *lbl_door5_1;
    QLabel *lbl_door3_7;
    QLabel *lbl_door1_8;
    QLabel *lbl_door4_4;
    QLabel *LBLTC1;
    QLabel *lbl_cab6_2;
    QLabel *lbl_door3_4;
    QLabel *lbl_door5_4;
    QLabel *lbl_door6_3;
    QLabel *LBLMP1;
    QLabel *lbl_door6_7;
    QLabel *lbl_cab1_1;
    QLabel *lbl_cab1_2;
    QLabel *LBLTC2;
    QLabel *lbl_door5_2;
    QLabel *lbl_door3_1;
    QLabel *LBLMP2;
    QLabel *lbl_door6_5;
    QLabel *lbl_cab6_1;
    QLabel *lbl_door4_6;
    QLabel *lbl_door1_7;
    QLabel *lbl_door5_7;
    QLabel *lbl_door3_2;
    QLabel *lbl_door2_1;
    QLabel *lbl_door2_8;
    QLabel *lbl_door4_3;
    QLabel *lbl_door2_4;
    QLabel *lbl_door4_1;
    QLabel *lbl_door6_8;
    QLabel *lbl_door1_4;
    QLabel *lbl_door6_1;
    QLabel *lbl_door2_6;
    QLabel *lbl_door1_6;
    QLabel *lbl_door6_4;
    QLabel *lbl_door5_8;
    QLabel *lbl_door6_2;
    QLabel *LBLM2;
    QLabel *lbl_door5_3;
    QLabel *lbl_door1_1;
    QLabel *lbl_door3_6;
    QLabel *lbl_door2_7;
    QLabel *lbl_door6_6;
    QLabel *lbl_door2_3;
    QLabel *lbl_door3_5;
    QLabel *lbl_door2_2;
    QLabel *lbl_door4_7;
    QLabel *lbl_door5_5;
    QLabel *lbl_door1_3;
    QLabel *lbl_door1_2;
    QLabel *lbl_door3_8;
    QLabel *lbl_door1_5;
    QLabel *lbl_door3_3;
    QLabel *lbl_door4_2;
    QLabel *lbl_door5_6;
    QLabel *lbl_quickBreak1;
    QLabel *lbl_quickBreak2;
    QLabel *lbl_quickBreak3;
    QLabel *lbl_quickBreak4;
    QLabel *lbl_tmp1;
    QLabel *lbl_tmp2;
    QLabel *lbl_tmp3;
    QLabel *lbl_tmp4;
    QLabel *lbl_tmp5;
    QLabel *lbl_tmp6;
    QLabel *lbl_tmpToken1;
    QLabel *lbl_panto1;
    QLabel *lbl_panto2;
    QLabel *lbl_tmpToken2;
    QLabel *lbl_tmpToken3;
    QLabel *lbl_tmpToken4;
    QLabel *lbl_tmpToken5;
    QLabel *lbl_tmpToken6;

    void setupUi(QWidget *VehicleTrainArea)
    {
        if (VehicleTrainArea->objectName().isEmpty())
            VehicleTrainArea->setObjectName(QString::fromUtf8("VehicleTrainArea"));
        VehicleTrainArea->resize(1024, 211);
        VehicleTrainArea->setStyleSheet(QString::fromUtf8("QWidget\n"
"{\n"
"	background-color: rgb(0,0,50);\n"
"}\n"
"QLabel\n"
"{\n"
"\n"
"font:24px,\"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"border:1px solid black;\n"
"}\n"
""));
        lbl_door4_5 = new QLabel(VehicleTrainArea);
        lbl_door4_5->setObjectName(QString::fromUtf8("lbl_door4_5"));
        lbl_door4_5->setGeometry(QRect(554, 150, 21, 25));
        lbl_door4_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_8 = new QLabel(VehicleTrainArea);
        lbl_door4_8->setObjectName(QString::fromUtf8("lbl_door4_8"));
        lbl_door4_8->setGeometry(QRect(520, 70, 21, 25));
        lbl_door4_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_5 = new QLabel(VehicleTrainArea);
        lbl_door2_5->setObjectName(QString::fromUtf8("lbl_door2_5"));
        lbl_door2_5->setGeometry(QRect(306, 70, 21, 25));
        lbl_door2_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLM1 = new QLabel(VehicleTrainArea);
        LBLM1->setObjectName(QString::fromUtf8("LBLM1"));
        LBLM1->setGeometry(QRect(370, 60, 140, 120));
        LBLM1->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_door5_1 = new QLabel(VehicleTrainArea);
        lbl_door5_1->setObjectName(QString::fromUtf8("lbl_door5_1"));
        lbl_door5_1->setGeometry(QRect(761, 150, 21, 25));
        lbl_door5_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_7 = new QLabel(VehicleTrainArea);
        lbl_door3_7->setObjectName(QString::fromUtf8("lbl_door3_7"));
        lbl_door3_7->setGeometry(QRect(480, 70, 21, 25));
        lbl_door3_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_8 = new QLabel(VehicleTrainArea);
        lbl_door1_8->setObjectName(QString::fromUtf8("lbl_door1_8"));
        lbl_door1_8->setGeometry(QRect(201, 150, 21, 25));
        lbl_door1_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_4 = new QLabel(VehicleTrainArea);
        lbl_door4_4->setObjectName(QString::fromUtf8("lbl_door4_4"));
        lbl_door4_4->setGeometry(QRect(588, 70, 21, 25));
        lbl_door4_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLTC1 = new QLabel(VehicleTrainArea);
        LBLTC1->setObjectName(QString::fromUtf8("LBLTC1"));
        LBLTC1->setGeometry(QRect(90, 60, 140, 120));
        LBLTC1->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_cab6_2 = new QLabel(VehicleTrainArea);
        lbl_cab6_2->setObjectName(QString::fromUtf8("lbl_cab6_2"));
        lbl_cab6_2->setGeometry(QRect(938, 70, 21, 25));
        lbl_cab6_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_4 = new QLabel(VehicleTrainArea);
        lbl_door3_4->setObjectName(QString::fromUtf8("lbl_door3_4"));
        lbl_door3_4->setGeometry(QRect(416, 150, 21, 25));
        lbl_door3_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door5_4 = new QLabel(VehicleTrainArea);
        lbl_door5_4->setObjectName(QString::fromUtf8("lbl_door5_4"));
        lbl_door5_4->setGeometry(QRect(728, 70, 21, 25));
        lbl_door5_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_3 = new QLabel(VehicleTrainArea);
        lbl_door6_3->setObjectName(QString::fromUtf8("lbl_door6_3"));
        lbl_door6_3->setGeometry(QRect(868, 150, 21, 25));
        lbl_door6_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLMP1 = new QLabel(VehicleTrainArea);
        LBLMP1->setObjectName(QString::fromUtf8("LBLMP1"));
        LBLMP1->setGeometry(QRect(230, 60, 140, 120));
        LBLMP1->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_door6_7 = new QLabel(VehicleTrainArea);
        lbl_door6_7->setObjectName(QString::fromUtf8("lbl_door6_7"));
        lbl_door6_7->setGeometry(QRect(800, 150, 21, 25));
        lbl_door6_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_cab1_1 = new QLabel(VehicleTrainArea);
        lbl_cab1_1->setObjectName(QString::fromUtf8("lbl_cab1_1"));
        lbl_cab1_1->setGeometry(QRect(64, 70, 21, 25));
        lbl_cab1_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_cab1_2 = new QLabel(VehicleTrainArea);
        lbl_cab1_2->setObjectName(QString::fromUtf8("lbl_cab1_2"));
        lbl_cab1_2->setGeometry(QRect(64, 150, 21, 25));
        lbl_cab1_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLTC2 = new QLabel(VehicleTrainArea);
        LBLTC2->setObjectName(QString::fromUtf8("LBLTC2"));
        LBLTC2->setGeometry(QRect(790, 60, 140, 120));
        LBLTC2->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_door5_2 = new QLabel(VehicleTrainArea);
        lbl_door5_2->setObjectName(QString::fromUtf8("lbl_door5_2"));
        lbl_door5_2->setGeometry(QRect(761, 70, 21, 25));
        lbl_door5_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_1 = new QLabel(VehicleTrainArea);
        lbl_door3_1->setObjectName(QString::fromUtf8("lbl_door3_1"));
        lbl_door3_1->setGeometry(QRect(380, 70, 21, 25));
        lbl_door3_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLMP2 = new QLabel(VehicleTrainArea);
        LBLMP2->setObjectName(QString::fromUtf8("LBLMP2"));
        LBLMP2->setGeometry(QRect(650, 60, 140, 120));
        LBLMP2->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_door6_5 = new QLabel(VehicleTrainArea);
        lbl_door6_5->setObjectName(QString::fromUtf8("lbl_door6_5"));
        lbl_door6_5->setGeometry(QRect(834, 150, 21, 25));
        lbl_door6_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_cab6_1 = new QLabel(VehicleTrainArea);
        lbl_cab6_1->setObjectName(QString::fromUtf8("lbl_cab6_1"));
        lbl_cab6_1->setGeometry(QRect(938, 150, 21, 25));
        lbl_cab6_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_6 = new QLabel(VehicleTrainArea);
        lbl_door4_6->setObjectName(QString::fromUtf8("lbl_door4_6"));
        lbl_door4_6->setGeometry(QRect(554, 70, 21, 25));
        lbl_door4_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_7 = new QLabel(VehicleTrainArea);
        lbl_door1_7->setObjectName(QString::fromUtf8("lbl_door1_7"));
        lbl_door1_7->setGeometry(QRect(201, 70, 21, 25));
        lbl_door1_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door5_7 = new QLabel(VehicleTrainArea);
        lbl_door5_7->setObjectName(QString::fromUtf8("lbl_door5_7"));
        lbl_door5_7->setGeometry(QRect(660, 150, 21, 25));
        lbl_door5_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_2 = new QLabel(VehicleTrainArea);
        lbl_door3_2->setObjectName(QString::fromUtf8("lbl_door3_2"));
        lbl_door3_2->setGeometry(QRect(380, 150, 21, 25));
        lbl_door3_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_1 = new QLabel(VehicleTrainArea);
        lbl_door2_1->setObjectName(QString::fromUtf8("lbl_door2_1"));
        lbl_door2_1->setGeometry(QRect(239, 70, 21, 25));
        lbl_door2_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_8 = new QLabel(VehicleTrainArea);
        lbl_door2_8->setObjectName(QString::fromUtf8("lbl_door2_8"));
        lbl_door2_8->setGeometry(QRect(340, 150, 21, 25));
        lbl_door2_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_3 = new QLabel(VehicleTrainArea);
        lbl_door4_3->setObjectName(QString::fromUtf8("lbl_door4_3"));
        lbl_door4_3->setGeometry(QRect(588, 150, 21, 25));
        lbl_door4_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_4 = new QLabel(VehicleTrainArea);
        lbl_door2_4->setObjectName(QString::fromUtf8("lbl_door2_4"));
        lbl_door2_4->setGeometry(QRect(272, 150, 21, 25));
        lbl_door2_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_1 = new QLabel(VehicleTrainArea);
        lbl_door4_1->setObjectName(QString::fromUtf8("lbl_door4_1"));
        lbl_door4_1->setGeometry(QRect(621, 150, 21, 25));
        lbl_door4_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_8 = new QLabel(VehicleTrainArea);
        lbl_door6_8->setObjectName(QString::fromUtf8("lbl_door6_8"));
        lbl_door6_8->setGeometry(QRect(800, 70, 21, 25));
        lbl_door6_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_4 = new QLabel(VehicleTrainArea);
        lbl_door1_4->setObjectName(QString::fromUtf8("lbl_door1_4"));
        lbl_door1_4->setGeometry(QRect(134, 150, 21, 25));
        lbl_door1_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_1 = new QLabel(VehicleTrainArea);
        lbl_door6_1->setObjectName(QString::fromUtf8("lbl_door6_1"));
        lbl_door6_1->setGeometry(QRect(901, 150, 21, 25));
        lbl_door6_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_6 = new QLabel(VehicleTrainArea);
        lbl_door2_6->setObjectName(QString::fromUtf8("lbl_door2_6"));
        lbl_door2_6->setGeometry(QRect(306, 150, 21, 25));
        lbl_door2_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_6 = new QLabel(VehicleTrainArea);
        lbl_door1_6->setObjectName(QString::fromUtf8("lbl_door1_6"));
        lbl_door1_6->setGeometry(QRect(168, 150, 21, 25));
        lbl_door1_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_4 = new QLabel(VehicleTrainArea);
        lbl_door6_4->setObjectName(QString::fromUtf8("lbl_door6_4"));
        lbl_door6_4->setGeometry(QRect(868, 70, 21, 25));
        lbl_door6_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door5_8 = new QLabel(VehicleTrainArea);
        lbl_door5_8->setObjectName(QString::fromUtf8("lbl_door5_8"));
        lbl_door5_8->setGeometry(QRect(660, 70, 21, 25));
        lbl_door5_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_2 = new QLabel(VehicleTrainArea);
        lbl_door6_2->setObjectName(QString::fromUtf8("lbl_door6_2"));
        lbl_door6_2->setGeometry(QRect(901, 70, 21, 25));
        lbl_door6_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        LBLM2 = new QLabel(VehicleTrainArea);
        LBLM2->setObjectName(QString::fromUtf8("LBLM2"));
        LBLM2->setGeometry(QRect(510, 60, 140, 120));
        LBLM2->setStyleSheet(QString::fromUtf8("background-color:rgb(170,170,170);"));
        lbl_door5_3 = new QLabel(VehicleTrainArea);
        lbl_door5_3->setObjectName(QString::fromUtf8("lbl_door5_3"));
        lbl_door5_3->setGeometry(QRect(728, 150, 21, 25));
        lbl_door5_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_1 = new QLabel(VehicleTrainArea);
        lbl_door1_1->setObjectName(QString::fromUtf8("lbl_door1_1"));
        lbl_door1_1->setGeometry(QRect(100, 70, 21, 25));
        lbl_door1_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_6 = new QLabel(VehicleTrainArea);
        lbl_door3_6->setObjectName(QString::fromUtf8("lbl_door3_6"));
        lbl_door3_6->setGeometry(QRect(446, 150, 21, 25));
        lbl_door3_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_7 = new QLabel(VehicleTrainArea);
        lbl_door2_7->setObjectName(QString::fromUtf8("lbl_door2_7"));
        lbl_door2_7->setGeometry(QRect(340, 70, 21, 25));
        lbl_door2_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door6_6 = new QLabel(VehicleTrainArea);
        lbl_door6_6->setObjectName(QString::fromUtf8("lbl_door6_6"));
        lbl_door6_6->setGeometry(QRect(834, 70, 21, 25));
        lbl_door6_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_3 = new QLabel(VehicleTrainArea);
        lbl_door2_3->setObjectName(QString::fromUtf8("lbl_door2_3"));
        lbl_door2_3->setGeometry(QRect(272, 70, 21, 25));
        lbl_door2_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_5 = new QLabel(VehicleTrainArea);
        lbl_door3_5->setObjectName(QString::fromUtf8("lbl_door3_5"));
        lbl_door3_5->setGeometry(QRect(446, 70, 21, 25));
        lbl_door3_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door2_2 = new QLabel(VehicleTrainArea);
        lbl_door2_2->setObjectName(QString::fromUtf8("lbl_door2_2"));
        lbl_door2_2->setGeometry(QRect(240, 150, 21, 25));
        lbl_door2_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_7 = new QLabel(VehicleTrainArea);
        lbl_door4_7->setObjectName(QString::fromUtf8("lbl_door4_7"));
        lbl_door4_7->setGeometry(QRect(520, 150, 21, 25));
        lbl_door4_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door5_5 = new QLabel(VehicleTrainArea);
        lbl_door5_5->setObjectName(QString::fromUtf8("lbl_door5_5"));
        lbl_door5_5->setGeometry(QRect(694, 150, 21, 25));
        lbl_door5_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_3 = new QLabel(VehicleTrainArea);
        lbl_door1_3->setObjectName(QString::fromUtf8("lbl_door1_3"));
        lbl_door1_3->setGeometry(QRect(134, 70, 21, 25));
        lbl_door1_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_2 = new QLabel(VehicleTrainArea);
        lbl_door1_2->setObjectName(QString::fromUtf8("lbl_door1_2"));
        lbl_door1_2->setGeometry(QRect(100, 150, 21, 25));
        lbl_door1_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_8 = new QLabel(VehicleTrainArea);
        lbl_door3_8->setObjectName(QString::fromUtf8("lbl_door3_8"));
        lbl_door3_8->setGeometry(QRect(480, 150, 21, 25));
        lbl_door3_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door1_5 = new QLabel(VehicleTrainArea);
        lbl_door1_5->setObjectName(QString::fromUtf8("lbl_door1_5"));
        lbl_door1_5->setGeometry(QRect(168, 70, 21, 25));
        lbl_door1_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door3_3 = new QLabel(VehicleTrainArea);
        lbl_door3_3->setObjectName(QString::fromUtf8("lbl_door3_3"));
        lbl_door3_3->setGeometry(QRect(414, 70, 21, 25));
        lbl_door3_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door4_2 = new QLabel(VehicleTrainArea);
        lbl_door4_2->setObjectName(QString::fromUtf8("lbl_door4_2"));
        lbl_door4_2->setGeometry(QRect(621, 70, 21, 25));
        lbl_door4_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_door5_6 = new QLabel(VehicleTrainArea);
        lbl_door5_6->setObjectName(QString::fromUtf8("lbl_door5_6"));
        lbl_door5_6->setGeometry(QRect(694, 70, 21, 25));
        lbl_door5_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_quickBreak1 = new QLabel(VehicleTrainArea);
        lbl_quickBreak1->setObjectName(QString::fromUtf8("lbl_quickBreak1"));
        lbl_quickBreak1->setGeometry(QRect(289, 110, 25, 25));
        lbl_quickBreak1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_quickBreak2 = new QLabel(VehicleTrainArea);
        lbl_quickBreak2->setObjectName(QString::fromUtf8("lbl_quickBreak2"));
        lbl_quickBreak2->setGeometry(QRect(429, 110, 25, 25));
        lbl_quickBreak2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_quickBreak3 = new QLabel(VehicleTrainArea);
        lbl_quickBreak3->setObjectName(QString::fromUtf8("lbl_quickBreak3"));
        lbl_quickBreak3->setGeometry(QRect(569, 110, 25, 25));
        lbl_quickBreak3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_quickBreak4 = new QLabel(VehicleTrainArea);
        lbl_quickBreak4->setObjectName(QString::fromUtf8("lbl_quickBreak4"));
        lbl_quickBreak4->setGeometry(QRect(709, 110, 25, 25));
        lbl_quickBreak4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp1 = new QLabel(VehicleTrainArea);
        lbl_tmp1->setObjectName(QString::fromUtf8("lbl_tmp1"));
        lbl_tmp1->setGeometry(QRect(130, 185, 41, 25));
        lbl_tmp1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp2 = new QLabel(VehicleTrainArea);
        lbl_tmp2->setObjectName(QString::fromUtf8("lbl_tmp2"));
        lbl_tmp2->setGeometry(QRect(270, 185, 41, 25));
        lbl_tmp2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp3 = new QLabel(VehicleTrainArea);
        lbl_tmp3->setObjectName(QString::fromUtf8("lbl_tmp3"));
        lbl_tmp3->setGeometry(QRect(410, 185, 41, 25));
        lbl_tmp3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp4 = new QLabel(VehicleTrainArea);
        lbl_tmp4->setObjectName(QString::fromUtf8("lbl_tmp4"));
        lbl_tmp4->setGeometry(QRect(550, 185, 41, 25));
        lbl_tmp4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp5 = new QLabel(VehicleTrainArea);
        lbl_tmp5->setObjectName(QString::fromUtf8("lbl_tmp5"));
        lbl_tmp5->setGeometry(QRect(690, 185, 41, 25));
        lbl_tmp5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmp6 = new QLabel(VehicleTrainArea);
        lbl_tmp6->setObjectName(QString::fromUtf8("lbl_tmp6"));
        lbl_tmp6->setGeometry(QRect(830, 185, 41, 25));
        lbl_tmp6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmpToken1 = new QLabel(VehicleTrainArea);
        lbl_tmpToken1->setObjectName(QString::fromUtf8("lbl_tmpToken1"));
        lbl_tmpToken1->setGeometry(QRect(180, 185, 25, 25));
        lbl_tmpToken1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        lbl_panto1 = new QLabel(VehicleTrainArea);
        lbl_panto1->setObjectName(QString::fromUtf8("lbl_panto1"));
        lbl_panto1->setGeometry(QRect(240, 4, 121, 51));
        lbl_panto1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_panto2 = new QLabel(VehicleTrainArea);
        lbl_panto2->setObjectName(QString::fromUtf8("lbl_panto2"));
        lbl_panto2->setGeometry(QRect(660, 4, 121, 51));
        lbl_panto2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lbl_tmpToken2 = new QLabel(VehicleTrainArea);
        lbl_tmpToken2->setObjectName(QString::fromUtf8("lbl_tmpToken2"));
        lbl_tmpToken2->setGeometry(QRect(320, 185, 25, 25));
        lbl_tmpToken2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        lbl_tmpToken3 = new QLabel(VehicleTrainArea);
        lbl_tmpToken3->setObjectName(QString::fromUtf8("lbl_tmpToken3"));
        lbl_tmpToken3->setGeometry(QRect(460, 185, 25, 25));
        lbl_tmpToken3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        lbl_tmpToken4 = new QLabel(VehicleTrainArea);
        lbl_tmpToken4->setObjectName(QString::fromUtf8("lbl_tmpToken4"));
        lbl_tmpToken4->setGeometry(QRect(600, 185, 25, 25));
        lbl_tmpToken4->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        lbl_tmpToken5 = new QLabel(VehicleTrainArea);
        lbl_tmpToken5->setObjectName(QString::fromUtf8("lbl_tmpToken5"));
        lbl_tmpToken5->setGeometry(QRect(740, 185, 25, 25));
        lbl_tmpToken5->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        lbl_tmpToken6 = new QLabel(VehicleTrainArea);
        lbl_tmpToken6->setObjectName(QString::fromUtf8("lbl_tmpToken6"));
        lbl_tmpToken6->setGeometry(QRect(880, 185, 25, 25));
        lbl_tmpToken6->setStyleSheet(QString::fromUtf8("border-image: url(:/images/image/tmptoken.png);"));
        LBLTC2->raise();
        LBLMP2->raise();
        LBLM1->raise();
        LBLM2->raise();
        LBLMP1->raise();
        LBLTC1->raise();
        lbl_door4_5->raise();
        lbl_door4_8->raise();
        lbl_door2_5->raise();
        lbl_door5_1->raise();
        lbl_door3_7->raise();
        lbl_door1_8->raise();
        lbl_door4_4->raise();
        lbl_cab6_2->raise();
        lbl_door3_4->raise();
        lbl_door5_4->raise();
        lbl_door6_3->raise();
        lbl_door6_7->raise();
        lbl_cab1_1->raise();
        lbl_cab1_2->raise();
        lbl_door5_2->raise();
        lbl_door3_1->raise();
        lbl_door6_5->raise();
        lbl_cab6_1->raise();
        lbl_door4_6->raise();
        lbl_door1_7->raise();
        lbl_door5_7->raise();
        lbl_door3_2->raise();
        lbl_door2_1->raise();
        lbl_door2_8->raise();
        lbl_door4_3->raise();
        lbl_door2_4->raise();
        lbl_door4_1->raise();
        lbl_door6_8->raise();
        lbl_door1_4->raise();
        lbl_door6_1->raise();
        lbl_door2_6->raise();
        lbl_door1_6->raise();
        lbl_door6_4->raise();
        lbl_door5_8->raise();
        lbl_door6_2->raise();
        lbl_door5_3->raise();
        lbl_door1_1->raise();
        lbl_door3_6->raise();
        lbl_door2_7->raise();
        lbl_door6_6->raise();
        lbl_door2_3->raise();
        lbl_door3_5->raise();
        lbl_door2_2->raise();
        lbl_door4_7->raise();
        lbl_door5_5->raise();
        lbl_door1_3->raise();
        lbl_door1_2->raise();
        lbl_door3_8->raise();
        lbl_door1_5->raise();
        lbl_door3_3->raise();
        lbl_door4_2->raise();
        lbl_door5_6->raise();
        lbl_quickBreak1->raise();
        lbl_quickBreak2->raise();
        lbl_quickBreak3->raise();
        lbl_quickBreak4->raise();
        lbl_tmp1->raise();
        lbl_tmp2->raise();
        lbl_tmp3->raise();
        lbl_tmp4->raise();
        lbl_tmp5->raise();
        lbl_tmp6->raise();
        lbl_tmpToken1->raise();
        lbl_panto1->raise();
        lbl_panto2->raise();
        lbl_tmpToken2->raise();
        lbl_tmpToken3->raise();
        lbl_tmpToken4->raise();
        lbl_tmpToken5->raise();
        lbl_tmpToken6->raise();

        retranslateUi(VehicleTrainArea);

        QMetaObject::connectSlotsByName(VehicleTrainArea);
    } // setupUi

    void retranslateUi(QWidget *VehicleTrainArea)
    {
        VehicleTrainArea->setWindowTitle(QApplication::translate("VehicleTrainArea", "Form", 0, QApplication::UnicodeUTF8));
        lbl_door4_5->setText(QString());
        lbl_door4_8->setText(QString());
        lbl_door2_5->setText(QString());
        LBLM1->setText(QString());
        lbl_door5_1->setText(QString());
        lbl_door3_7->setText(QString());
        lbl_door1_8->setText(QString());
        lbl_door4_4->setText(QString());
        LBLTC1->setText(QString());
        lbl_cab6_2->setText(QString());
        lbl_door3_4->setText(QString());
        lbl_door5_4->setText(QString());
        lbl_door6_3->setText(QString());
        LBLMP1->setText(QString());
        lbl_door6_7->setText(QString());
        lbl_cab1_1->setText(QString());
        lbl_cab1_2->setText(QString());
        LBLTC2->setText(QString());
        lbl_door5_2->setText(QString());
        lbl_door3_1->setText(QString());
        LBLMP2->setText(QString());
        lbl_door6_5->setText(QString());
        lbl_cab6_1->setText(QString());
        lbl_door4_6->setText(QString());
        lbl_door1_7->setText(QString());
        lbl_door5_7->setText(QString());
        lbl_door3_2->setText(QString());
        lbl_door2_1->setText(QString());
        lbl_door2_8->setText(QString());
        lbl_door4_3->setText(QString());
        lbl_door2_4->setText(QString());
        lbl_door4_1->setText(QString());
        lbl_door6_8->setText(QString());
        lbl_door1_4->setText(QString());
        lbl_door6_1->setText(QString());
        lbl_door2_6->setText(QString());
        lbl_door1_6->setText(QString());
        lbl_door6_4->setText(QString());
        lbl_door5_8->setText(QString());
        lbl_door6_2->setText(QString());
        LBLM2->setText(QString());
        lbl_door5_3->setText(QString());
        lbl_door1_1->setText(QString());
        lbl_door3_6->setText(QString());
        lbl_door2_7->setText(QString());
        lbl_door6_6->setText(QString());
        lbl_door2_3->setText(QString());
        lbl_door3_5->setText(QString());
        lbl_door2_2->setText(QString());
        lbl_door4_7->setText(QString());
        lbl_door5_5->setText(QString());
        lbl_door1_3->setText(QString());
        lbl_door1_2->setText(QString());
        lbl_door3_8->setText(QString());
        lbl_door1_5->setText(QString());
        lbl_door3_3->setText(QString());
        lbl_door4_2->setText(QString());
        lbl_door5_6->setText(QString());
        lbl_quickBreak1->setText(QString());
        lbl_quickBreak2->setText(QString());
        lbl_quickBreak3->setText(QString());
        lbl_quickBreak4->setText(QString());
        lbl_tmp1->setText(QString());
        lbl_tmp2->setText(QString());
        lbl_tmp3->setText(QString());
        lbl_tmp4->setText(QString());
        lbl_tmp5->setText(QString());
        lbl_tmp6->setText(QString());
        lbl_tmpToken1->setText(QString());
        lbl_panto1->setText(QString());
        lbl_panto2->setText(QString());
        lbl_tmpToken2->setText(QString());
        lbl_tmpToken3->setText(QString());
        lbl_tmpToken4->setText(QString());
        lbl_tmpToken5->setText(QString());
        lbl_tmpToken6->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class VehicleTrainArea: public Ui_VehicleTrainArea {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VEHICLETRAINAREA_H
